version: '2'

services:
    influxdb:
        build: influxdb
        container_name: influxdb
        image: influxdb-hackaday
        env_file: config.env
        ports:
            - '8086:8086'
            - '8083:8083'
        volumes:
            - ../influxdb_data:/var/lib/influxdb
            
    grafana:
        image: fg2it/grafana-armhf:v4.1.2
        container_name: grafana
        env_file: config.env
        links:
          - influxdb
        ports:
          - '3000:3000'
        depends_on:
          - influxdb
